package:
  name: bcolz 

source:
    git_rev: v1.7.0
    git_url: https://github.com/pypa/setuptools_scm.git

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy

test:
  requires:
    - unittest2 [py26]
    - mock [py2k]
    - pandas

  commands:
    - python -c "import bcolz; bcolz.test()"

about:
  home: http://bcolz.blosc.org/
  license: BSD
