package:
  name: bcolz 

build:
    preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools_scm 
    - cython
    - numpy

  run:
    - python
    - numpy

test:
  requires:
    - unittest2 [py26]
    - mock [py2k]
    - pandas

  commands:
    - python -c "import bcolz; bcolz.test()"

about:
  home: http://bcolz.blosc.org/
  license: BSD
