{% set name = "bcolz-zipline" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: b8c212df89901110fb2b48efe96853a4

build:
  number: 0
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]    -
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - toml
    - pip
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - python -c "import bcolz; bcolz.test()"
  requires:
    - numpy

about:
  home: https://github.com/stefan-jansen/bcolz-zipline
  summary: Columnar and compressed data containers.
  license: BSD-1-Clause
  license_file: LICENSES/BCOLZ.txt


